#!/bin/sh

#############################
### Environment variables ###
#############################

- PATH
- VIMRUNTINME

# Add $HOME/local/bin to the searched libraries of binaries
PATH=$HOME/local/bin:$PATH
export PATH

# Set VIM runtime library to local version
export VIMRUNTIME=~/lib/build/vim/runtime/
