#!/bin/sh

#

##########################################
### --- File permissions/ownership --- ###
##########################################

# set properties of the file
chmod u+x filename

#########################
### --- Searching --- ###
#########################

### ls
# recently modified
ls -lt

# List all files in the subdirs with full path displayed
find . -type f -printf "%p\n"

####################
### File reading ###
####################

# Print out the first 'n' lines of the file
head -n <number of lines>

# Print out the last 'n' lines of the file
tail -n <number of lines>

##### Movement in directories ####

#move up several directories: 
cd ../../..

#String concatenation:
string1_string2

#giveback variable value
$

# String replacement/evaluation
${stringvariblename} 

# Replace a string a file
set -i "s/oldstring/newstring/g" inputfile
set "s/oldstring/newstring/g" <inputfile> outfile

#Search in bash
CTRL+R

# print full path
readlink -f FILENAME

### How to tar multiple directories
tar czf directories.tar dir1 dir2 dir3 ...

# Untarring
tar zxvf filename

# Loop over lines in an external file
while read name
do
    echo "$name"
done < names.txt

# Get the filebasename (in Makefile)
${PIDconfigfile##*/}

###################################
# If 'Segmentation' sttring is found do sg.
workdir=Enigma_HighMult_Full_PIDConfig_default_trkCorr_no
listfile=list_failedjobs_$workdir

rm $listfile
cd $workdir

FILES=$(find . -name \* -print)

rm $listfile
touch $listfile

for f in $FILES
do
  if grep -q 'Segmentation' $f; then
  grep -o "\<root://.*.root\>" $f >> $listfile
  fi
done

mv $listfile ../$listfile

### Look at the functions of a library
nm -Ca <library>

######################
### Creating links ###
######################

# To create a symbolic link
ln -s {/path/to/file-name} {link-name}

# To create hard link
ln {file.txt} {hard-link}

#################
### Libraries ###
#################

# Check if library <libname> is installed
ldconfig -p | grep <libname>
