#!/bin/bash

########################################################
### Computer Architecture and Hardware info commands ###
########################################################

# Get info about kernel and architecture
uname -a

# Linux standard base distribution information
lsb_release -d

# Get number of cores
nproc
